anchor_version = "0.25.0"

[provider]
cluster = "mainnet"
wallet = "oracle.key"

[programs.mainnet]
questing = "9iMuz8Lf27R9Y2jQhWM1wrSVtPB4Tt5wqkh1opjMTK11"
swapper = "EocXeJ7KvMZD9k1mVWVHP6KWpRhsLP666wtahSBEMawr"


[programs.localnet]
questing = "9iMuz8Lf27R9Y2jQhWM1wrSVtPB4Tt5wqkh1opjMTK11"
swapper = "EocXeJ7KvMZD9k1mVWVHP6KWpRhsLP666wtahSBEMawr"
