// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type QuestAccount struct {
	Quest       ag_solanago.PublicKey
	Index       uint64
	StartTime   int64
	EndTime     int64
	Initializer ag_solanago.PublicKey
	Completed   *bool `bin:"optional"`
	LastClaim   int64
}

var QuestAccountDiscriminator = [8]byte{150, 179, 23, 90, 199, 60, 121, 92}

func (obj QuestAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Quest` param:
	err = encoder.Encode(obj.Quest)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `StartTime` param:
	err = encoder.Encode(obj.StartTime)
	if err != nil {
		return err
	}
	// Serialize `EndTime` param:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return err
	}
	// Serialize `Initializer` param:
	err = encoder.Encode(obj.Initializer)
	if err != nil {
		return err
	}
	// Serialize `Completed` param (optional):
	{
		if obj.Completed == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Completed)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `LastClaim` param:
	err = encoder.Encode(obj.LastClaim)
	if err != nil {
		return err
	}
	return nil
}

func (obj *QuestAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[150 179 23 90 199 60 121 92]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Quest`:
	err = decoder.Decode(&obj.Quest)
	if err != nil {
		return err
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `StartTime`:
	err = decoder.Decode(&obj.StartTime)
	if err != nil {
		return err
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return err
	}
	// Deserialize `Initializer`:
	err = decoder.Decode(&obj.Initializer)
	if err != nil {
		return err
	}
	// Deserialize `Completed` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Completed)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `LastClaim`:
	err = decoder.Decode(&obj.LastClaim)
	if err != nil {
		return err
	}
	return nil
}

type Quests struct {
	Quests  uint64
	Oracle  ag_solanago.PublicKey
	Rewards []Reward
}

var QuestsDiscriminator = [8]byte{126, 222, 157, 18, 210, 20, 186, 78}

func (obj Quests) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestsDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Quests` param:
	err = encoder.Encode(obj.Quests)
	if err != nil {
		return err
	}
	// Serialize `Oracle` param:
	err = encoder.Encode(obj.Oracle)
	if err != nil {
		return err
	}
	// Serialize `Rewards` param:
	err = encoder.Encode(obj.Rewards)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Quests) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestsDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[126 222 157 18 210 20 186 78]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Quests`:
	err = decoder.Decode(&obj.Quests)
	if err != nil {
		return err
	}
	// Deserialize `Oracle`:
	err = decoder.Decode(&obj.Oracle)
	if err != nil {
		return err
	}
	// Deserialize `Rewards`:
	err = decoder.Decode(&obj.Rewards)
	if err != nil {
		return err
	}
	return nil
}

type Quest struct {
	Enabled         bool
	Index           uint64
	Name            string
	Duration        int64
	Oracle          ag_solanago.PublicKey
	RequiredLevel   uint64
	RequiredXp      uint64
	WlCandyMachines []ag_solanago.PublicKey
	Rewards         []Reward
	Tender          *Tender  `bin:"optional"`
	TenderSplits    *[]Split `bin:"optional"`
	Xp              uint64
	StakingConfig   *StakingConfig `bin:"optional"`
	PairsConfig     *PairsConfig   `bin:"optional"`
}

var QuestDiscriminator = [8]byte{68, 78, 51, 23, 204, 27, 76, 132}

func (obj Quest) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Enabled` param:
	err = encoder.Encode(obj.Enabled)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Duration` param:
	err = encoder.Encode(obj.Duration)
	if err != nil {
		return err
	}
	// Serialize `Oracle` param:
	err = encoder.Encode(obj.Oracle)
	if err != nil {
		return err
	}
	// Serialize `RequiredLevel` param:
	err = encoder.Encode(obj.RequiredLevel)
	if err != nil {
		return err
	}
	// Serialize `RequiredXp` param:
	err = encoder.Encode(obj.RequiredXp)
	if err != nil {
		return err
	}
	// Serialize `WlCandyMachines` param:
	err = encoder.Encode(obj.WlCandyMachines)
	if err != nil {
		return err
	}
	// Serialize `Rewards` param:
	err = encoder.Encode(obj.Rewards)
	if err != nil {
		return err
	}
	// Serialize `Tender` param (optional):
	{
		if obj.Tender == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Tender)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `TenderSplits` param (optional):
	{
		if obj.TenderSplits == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.TenderSplits)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	// Serialize `StakingConfig` param (optional):
	{
		if obj.StakingConfig == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.StakingConfig)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `PairsConfig` param (optional):
	{
		if obj.PairsConfig == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.PairsConfig)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (obj *Quest) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[68 78 51 23 204 27 76 132]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Enabled`:
	err = decoder.Decode(&obj.Enabled)
	if err != nil {
		return err
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Duration`:
	err = decoder.Decode(&obj.Duration)
	if err != nil {
		return err
	}
	// Deserialize `Oracle`:
	err = decoder.Decode(&obj.Oracle)
	if err != nil {
		return err
	}
	// Deserialize `RequiredLevel`:
	err = decoder.Decode(&obj.RequiredLevel)
	if err != nil {
		return err
	}
	// Deserialize `RequiredXp`:
	err = decoder.Decode(&obj.RequiredXp)
	if err != nil {
		return err
	}
	// Deserialize `WlCandyMachines`:
	err = decoder.Decode(&obj.WlCandyMachines)
	if err != nil {
		return err
	}
	// Deserialize `Rewards`:
	err = decoder.Decode(&obj.Rewards)
	if err != nil {
		return err
	}
	// Deserialize `Tender` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Tender)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `TenderSplits` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.TenderSplits)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	// Deserialize `StakingConfig` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.StakingConfig)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `PairsConfig` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.PairsConfig)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

type Questor struct {
	Initializer ag_solanago.PublicKey
	Xp          uint64
}

var QuestorDiscriminator = [8]byte{103, 165, 162, 230, 97, 74, 133, 76}

func (obj Questor) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestorDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Initializer` param:
	err = encoder.Encode(obj.Initializer)
	if err != nil {
		return err
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Questor) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestorDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[103 165 162 230 97 74 133 76]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Initializer`:
	err = decoder.Decode(&obj.Initializer)
	if err != nil {
		return err
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

type Questee struct {
	Owner          ag_solanago.PublicKey
	PixelballzMint ag_solanago.PublicKey
	Quests         uint64
	Xp             uint64
}

var QuesteeDiscriminator = [8]byte{239, 51, 124, 161, 92, 184, 172, 208}

func (obj Questee) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuesteeDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Owner` param:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return err
	}
	// Serialize `PixelballzMint` param:
	err = encoder.Encode(obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Serialize `Quests` param:
	err = encoder.Encode(obj.Quests)
	if err != nil {
		return err
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Questee) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuesteeDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[239 51 124 161 92 184 172 208]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return err
	}
	// Deserialize `PixelballzMint`:
	err = decoder.Decode(&obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Deserialize `Quests`:
	err = decoder.Decode(&obj.Quests)
	if err != nil {
		return err
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

type QuestQuesteeEndReceipt struct {
	Owner          ag_solanago.PublicKey
	PixelballzMint ag_solanago.PublicKey
	RewardMint     ag_solanago.PublicKey
	Amount         uint64
}

var QuestQuesteeEndReceiptDiscriminator = [8]byte{229, 239, 65, 24, 83, 169, 199, 238}

func (obj QuestQuesteeEndReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestQuesteeEndReceiptDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Owner` param:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return err
	}
	// Serialize `PixelballzMint` param:
	err = encoder.Encode(obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Serialize `RewardMint` param:
	err = encoder.Encode(obj.RewardMint)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

func (obj *QuestQuesteeEndReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestQuesteeEndReceiptDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[229 239 65 24 83 169 199 238]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return err
	}
	// Deserialize `PixelballzMint`:
	err = decoder.Decode(&obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Deserialize `RewardMint`:
	err = decoder.Decode(&obj.RewardMint)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

type QuestRecorder struct {
	Proposals   uint64
	Quest       ag_solanago.PublicKey
	Initializer ag_solanago.PublicKey
	Oracle      ag_solanago.PublicKey
	Staked      []ag_solanago.PublicKey
}

var QuestRecorderDiscriminator = [8]byte{47, 98, 221, 127, 182, 240, 4, 253}

func (obj QuestRecorder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestRecorderDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Proposals` param:
	err = encoder.Encode(obj.Proposals)
	if err != nil {
		return err
	}
	// Serialize `Quest` param:
	err = encoder.Encode(obj.Quest)
	if err != nil {
		return err
	}
	// Serialize `Initializer` param:
	err = encoder.Encode(obj.Initializer)
	if err != nil {
		return err
	}
	// Serialize `Oracle` param:
	err = encoder.Encode(obj.Oracle)
	if err != nil {
		return err
	}
	// Serialize `Staked` param:
	err = encoder.Encode(obj.Staked)
	if err != nil {
		return err
	}
	return nil
}

func (obj *QuestRecorder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestRecorderDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[47 98 221 127 182 240 4 253]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Proposals`:
	err = decoder.Decode(&obj.Proposals)
	if err != nil {
		return err
	}
	// Deserialize `Quest`:
	err = decoder.Decode(&obj.Quest)
	if err != nil {
		return err
	}
	// Deserialize `Initializer`:
	err = decoder.Decode(&obj.Initializer)
	if err != nil {
		return err
	}
	// Deserialize `Oracle`:
	err = decoder.Decode(&obj.Oracle)
	if err != nil {
		return err
	}
	// Deserialize `Staked`:
	err = decoder.Decode(&obj.Staked)
	if err != nil {
		return err
	}
	return nil
}

type QuestProposal struct {
	Index           uint64
	Fulfilled       bool
	Started         bool
	Finished        bool
	Withdrawn       bool
	DepositingLeft  []ag_solanago.PublicKey
	DepositingRight []ag_solanago.PublicKey
	RecordLeft      []bool
	RecordRight     []bool
}

var QuestProposalDiscriminator = [8]byte{255, 30, 189, 25, 29, 184, 163, 186}

func (obj QuestProposal) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestProposalDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `Fulfilled` param:
	err = encoder.Encode(obj.Fulfilled)
	if err != nil {
		return err
	}
	// Serialize `Started` param:
	err = encoder.Encode(obj.Started)
	if err != nil {
		return err
	}
	// Serialize `Finished` param:
	err = encoder.Encode(obj.Finished)
	if err != nil {
		return err
	}
	// Serialize `Withdrawn` param:
	err = encoder.Encode(obj.Withdrawn)
	if err != nil {
		return err
	}
	// Serialize `DepositingLeft` param:
	err = encoder.Encode(obj.DepositingLeft)
	if err != nil {
		return err
	}
	// Serialize `DepositingRight` param:
	err = encoder.Encode(obj.DepositingRight)
	if err != nil {
		return err
	}
	// Serialize `RecordLeft` param:
	err = encoder.Encode(obj.RecordLeft)
	if err != nil {
		return err
	}
	// Serialize `RecordRight` param:
	err = encoder.Encode(obj.RecordRight)
	if err != nil {
		return err
	}
	return nil
}

func (obj *QuestProposal) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestProposalDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[255 30 189 25 29 184 163 186]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `Fulfilled`:
	err = decoder.Decode(&obj.Fulfilled)
	if err != nil {
		return err
	}
	// Deserialize `Started`:
	err = decoder.Decode(&obj.Started)
	if err != nil {
		return err
	}
	// Deserialize `Finished`:
	err = decoder.Decode(&obj.Finished)
	if err != nil {
		return err
	}
	// Deserialize `Withdrawn`:
	err = decoder.Decode(&obj.Withdrawn)
	if err != nil {
		return err
	}
	// Deserialize `DepositingLeft`:
	err = decoder.Decode(&obj.DepositingLeft)
	if err != nil {
		return err
	}
	// Deserialize `DepositingRight`:
	err = decoder.Decode(&obj.DepositingRight)
	if err != nil {
		return err
	}
	// Deserialize `RecordLeft`:
	err = decoder.Decode(&obj.RecordLeft)
	if err != nil {
		return err
	}
	// Deserialize `RecordRight`:
	err = decoder.Decode(&obj.RecordRight)
	if err != nil {
		return err
	}
	return nil
}
