// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type QuestAccount struct {
	Index            uint64
	StartTime        int64
	EndTime          int64
	DepositTokenMint ag_solanago.PublicKey
	Initializer      ag_solanago.PublicKey
	Completed        *bool `bin:"optional"`
}

var QuestAccountDiscriminator = [8]byte{150, 179, 23, 90, 199, 60, 121, 92}

func (obj QuestAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `StartTime` param:
	err = encoder.Encode(obj.StartTime)
	if err != nil {
		return err
	}
	// Serialize `EndTime` param:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return err
	}
	// Serialize `DepositTokenMint` param:
	err = encoder.Encode(obj.DepositTokenMint)
	if err != nil {
		return err
	}
	// Serialize `Initializer` param:
	err = encoder.Encode(obj.Initializer)
	if err != nil {
		return err
	}
	// Serialize `Completed` param (optional):
	{
		if obj.Completed == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Completed)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (obj *QuestAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[150 179 23 90 199 60 121 92]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `StartTime`:
	err = decoder.Decode(&obj.StartTime)
	if err != nil {
		return err
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return err
	}
	// Deserialize `DepositTokenMint`:
	err = decoder.Decode(&obj.DepositTokenMint)
	if err != nil {
		return err
	}
	// Deserialize `Initializer`:
	err = decoder.Decode(&obj.Initializer)
	if err != nil {
		return err
	}
	// Deserialize `Completed` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Completed)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

type Quests struct {
	Quests  uint64
	Oracle  ag_solanago.PublicKey
	Rewards []Reward
}

var QuestsDiscriminator = [8]byte{126, 222, 157, 18, 210, 20, 186, 78}

func (obj Quests) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestsDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Quests` param:
	err = encoder.Encode(obj.Quests)
	if err != nil {
		return err
	}
	// Serialize `Oracle` param:
	err = encoder.Encode(obj.Oracle)
	if err != nil {
		return err
	}
	// Serialize `Rewards` param:
	err = encoder.Encode(obj.Rewards)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Quests) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestsDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[126 222 157 18 210 20 186 78]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Quests`:
	err = decoder.Decode(&obj.Quests)
	if err != nil {
		return err
	}
	// Deserialize `Oracle`:
	err = decoder.Decode(&obj.Oracle)
	if err != nil {
		return err
	}
	// Deserialize `Rewards`:
	err = decoder.Decode(&obj.Rewards)
	if err != nil {
		return err
	}
	return nil
}

type RewardToken struct {
	MintAddress ag_solanago.PublicKey
	Threshold   uint8
	Amount      uint64
}

var RewardTokenDiscriminator = [8]byte{234, 93, 249, 45, 69, 185, 102, 28}

func (obj RewardToken) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(RewardTokenDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `MintAddress` param:
	err = encoder.Encode(obj.MintAddress)
	if err != nil {
		return err
	}
	// Serialize `Threshold` param:
	err = encoder.Encode(obj.Threshold)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

func (obj *RewardToken) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(RewardTokenDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[234 93 249 45 69 185 102 28]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `MintAddress`:
	err = decoder.Decode(&obj.MintAddress)
	if err != nil {
		return err
	}
	// Deserialize `Threshold`:
	err = decoder.Decode(&obj.Threshold)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

type Quest struct {
	Enabled         bool
	Index           uint64
	Name            string
	Duration        int64
	Oracle          ag_solanago.PublicKey
	RequiredLevel   uint64
	RequiredXp      uint64
	WlCandyMachines []ag_solanago.PublicKey
	Entitlement     *Reward  `bin:"optional"`
	Tender          *Tender  `bin:"optional"`
	TenderSplits    *[]Split `bin:"optional"`
	Xp              uint64
}

var QuestDiscriminator = [8]byte{68, 78, 51, 23, 204, 27, 76, 132}

func (obj Quest) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Enabled` param:
	err = encoder.Encode(obj.Enabled)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Duration` param:
	err = encoder.Encode(obj.Duration)
	if err != nil {
		return err
	}
	// Serialize `Oracle` param:
	err = encoder.Encode(obj.Oracle)
	if err != nil {
		return err
	}
	// Serialize `RequiredLevel` param:
	err = encoder.Encode(obj.RequiredLevel)
	if err != nil {
		return err
	}
	// Serialize `RequiredXp` param:
	err = encoder.Encode(obj.RequiredXp)
	if err != nil {
		return err
	}
	// Serialize `WlCandyMachines` param:
	err = encoder.Encode(obj.WlCandyMachines)
	if err != nil {
		return err
	}
	// Serialize `Entitlement` param (optional):
	{
		if obj.Entitlement == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Entitlement)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Tender` param (optional):
	{
		if obj.Tender == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Tender)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `TenderSplits` param (optional):
	{
		if obj.TenderSplits == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.TenderSplits)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Quest) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[68 78 51 23 204 27 76 132]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Enabled`:
	err = decoder.Decode(&obj.Enabled)
	if err != nil {
		return err
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Duration`:
	err = decoder.Decode(&obj.Duration)
	if err != nil {
		return err
	}
	// Deserialize `Oracle`:
	err = decoder.Decode(&obj.Oracle)
	if err != nil {
		return err
	}
	// Deserialize `RequiredLevel`:
	err = decoder.Decode(&obj.RequiredLevel)
	if err != nil {
		return err
	}
	// Deserialize `RequiredXp`:
	err = decoder.Decode(&obj.RequiredXp)
	if err != nil {
		return err
	}
	// Deserialize `WlCandyMachines`:
	err = decoder.Decode(&obj.WlCandyMachines)
	if err != nil {
		return err
	}
	// Deserialize `Entitlement` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Entitlement)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `Tender` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Tender)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `TenderSplits` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.TenderSplits)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

type Questor struct {
	Initializer ag_solanago.PublicKey
	Xp          uint64
}

var QuestorDiscriminator = [8]byte{103, 165, 162, 230, 97, 74, 133, 76}

func (obj Questor) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestorDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Initializer` param:
	err = encoder.Encode(obj.Initializer)
	if err != nil {
		return err
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Questor) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestorDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[103 165 162 230 97 74 133 76]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Initializer`:
	err = decoder.Decode(&obj.Initializer)
	if err != nil {
		return err
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

type Questee struct {
	Owner          ag_solanago.PublicKey
	PixelballzMint ag_solanago.PublicKey
	Quests         uint64
	Xp             uint64
}

var QuesteeDiscriminator = [8]byte{239, 51, 124, 161, 92, 184, 172, 208}

func (obj Questee) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuesteeDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Owner` param:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return err
	}
	// Serialize `PixelballzMint` param:
	err = encoder.Encode(obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Serialize `Quests` param:
	err = encoder.Encode(obj.Quests)
	if err != nil {
		return err
	}
	// Serialize `Xp` param:
	err = encoder.Encode(obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Questee) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuesteeDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[239 51 124 161 92 184 172 208]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return err
	}
	// Deserialize `PixelballzMint`:
	err = decoder.Decode(&obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Deserialize `Quests`:
	err = decoder.Decode(&obj.Quests)
	if err != nil {
		return err
	}
	// Deserialize `Xp`:
	err = decoder.Decode(&obj.Xp)
	if err != nil {
		return err
	}
	return nil
}

type QuestQuesteeEndReceipt struct {
	Owner          ag_solanago.PublicKey
	PixelballzMint ag_solanago.PublicKey
	RewardMint     ag_solanago.PublicKey
	Amount         uint64
}

var QuestQuesteeEndReceiptDiscriminator = [8]byte{229, 239, 65, 24, 83, 169, 199, 238}

func (obj QuestQuesteeEndReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(QuestQuesteeEndReceiptDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Owner` param:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return err
	}
	// Serialize `PixelballzMint` param:
	err = encoder.Encode(obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Serialize `RewardMint` param:
	err = encoder.Encode(obj.RewardMint)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

func (obj *QuestQuesteeEndReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(QuestQuesteeEndReceiptDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[229 239 65 24 83 169 199 238]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return err
	}
	// Deserialize `PixelballzMint`:
	err = decoder.Decode(&obj.PixelballzMint)
	if err != nil {
		return err
	}
	// Deserialize `RewardMint`:
	err = decoder.Decode(&obj.RewardMint)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
