// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EndQuest is the `endQuest` instruction.
type EndQuest struct {
	QuestProposalIndex *uint64
	QuestProposalBump  *uint8
	QuestRecorderBump  *uint8
	QuestsBump         *uint8
	QuestBump          *uint8

	// [0] = [WRITE] questRecorder
	//
	// [1] = [WRITE] questAcc
	//
	// [2] = [WRITE] questProposal
	//
	// [3] = [WRITE] quest
	//
	// [4] = [WRITE] quests
	//
	// [5] = [WRITE, SIGNER] initializer
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] systemProgram
	//
	// [8] = [] rent
	//
	// [9] = [] associatedTokenProgram
	//
	// [10] = [] slotHashes
	//
	// [11] = [WRITE] oracle
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEndQuestInstructionBuilder creates a new `EndQuest` instruction builder.
func NewEndQuestInstructionBuilder() *EndQuest {
	nd := &EndQuest{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
	return nd
}

// SetQuestProposalIndex sets the "questProposalIndex" parameter.
func (inst *EndQuest) SetQuestProposalIndex(questProposalIndex uint64) *EndQuest {
	inst.QuestProposalIndex = &questProposalIndex
	return inst
}

// SetQuestProposalBump sets the "questProposalBump" parameter.
func (inst *EndQuest) SetQuestProposalBump(questProposalBump uint8) *EndQuest {
	inst.QuestProposalBump = &questProposalBump
	return inst
}

// SetQuestRecorderBump sets the "questRecorderBump" parameter.
func (inst *EndQuest) SetQuestRecorderBump(questRecorderBump uint8) *EndQuest {
	inst.QuestRecorderBump = &questRecorderBump
	return inst
}

// SetQuestsBump sets the "questsBump" parameter.
func (inst *EndQuest) SetQuestsBump(questsBump uint8) *EndQuest {
	inst.QuestsBump = &questsBump
	return inst
}

// SetQuestBump sets the "questBump" parameter.
func (inst *EndQuest) SetQuestBump(questBump uint8) *EndQuest {
	inst.QuestBump = &questBump
	return inst
}

// SetQuestRecorderAccount sets the "questRecorder" account.
func (inst *EndQuest) SetQuestRecorderAccount(questRecorder ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(questRecorder).WRITE()
	return inst
}

// GetQuestRecorderAccount gets the "questRecorder" account.
func (inst *EndQuest) GetQuestRecorderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetQuestAccAccount sets the "questAcc" account.
func (inst *EndQuest) SetQuestAccAccount(questAcc ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(questAcc).WRITE()
	return inst
}

// GetQuestAccAccount gets the "questAcc" account.
func (inst *EndQuest) GetQuestAccAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetQuestProposalAccount sets the "questProposal" account.
func (inst *EndQuest) SetQuestProposalAccount(questProposal ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(questProposal).WRITE()
	return inst
}

// GetQuestProposalAccount gets the "questProposal" account.
func (inst *EndQuest) GetQuestProposalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQuestAccount sets the "quest" account.
func (inst *EndQuest) SetQuestAccount(quest ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(quest).WRITE()
	return inst
}

// GetQuestAccount gets the "quest" account.
func (inst *EndQuest) GetQuestAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQuestsAccount sets the "quests" account.
func (inst *EndQuest) SetQuestsAccount(quests ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(quests).WRITE()
	return inst
}

// GetQuestsAccount gets the "quests" account.
func (inst *EndQuest) GetQuestsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetInitializerAccount sets the "initializer" account.
func (inst *EndQuest) SetInitializerAccount(initializer ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *EndQuest) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *EndQuest) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *EndQuest) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EndQuest) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EndQuest) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetRentAccount sets the "rent" account.
func (inst *EndQuest) SetRentAccount(rent ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *EndQuest) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *EndQuest) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *EndQuest) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSlotHashesAccount sets the "slotHashes" account.
func (inst *EndQuest) SetSlotHashesAccount(slotHashes ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(slotHashes)
	return inst
}

// GetSlotHashesAccount gets the "slotHashes" account.
func (inst *EndQuest) GetSlotHashesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetOracleAccount sets the "oracle" account.
func (inst *EndQuest) SetOracleAccount(oracle ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(oracle).WRITE()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *EndQuest) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

func (inst EndQuest) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EndQuest,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EndQuest) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EndQuest) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.QuestProposalIndex == nil {
			return errors.New("QuestProposalIndex parameter is not set")
		}
		if inst.QuestProposalBump == nil {
			return errors.New("QuestProposalBump parameter is not set")
		}
		if inst.QuestRecorderBump == nil {
			return errors.New("QuestRecorderBump parameter is not set")
		}
		if inst.QuestsBump == nil {
			return errors.New("QuestsBump parameter is not set")
		}
		if inst.QuestBump == nil {
			return errors.New("QuestBump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.QuestRecorder is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.QuestAcc is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.QuestProposal is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Quest is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Quests is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SlotHashes is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Oracle is not set")
		}
	}
	return nil
}

func (inst *EndQuest) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EndQuest")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("QuestProposalIndex", *inst.QuestProposalIndex))
						paramsBranch.Child(ag_format.Param(" QuestProposalBump", *inst.QuestProposalBump))
						paramsBranch.Child(ag_format.Param(" QuestRecorderBump", *inst.QuestRecorderBump))
						paramsBranch.Child(ag_format.Param("        QuestsBump", *inst.QuestsBump))
						paramsBranch.Child(ag_format.Param("         QuestBump", *inst.QuestBump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=12]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         questRecorder", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("              questAcc", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         questProposal", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                 quest", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                quests", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("           initializer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                  rent", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("            slotHashes", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("                oracle", inst.AccountMetaSlice.Get(11)))
					})
				})
		})
}

func (obj EndQuest) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `QuestProposalIndex` param:
	err = encoder.Encode(obj.QuestProposalIndex)
	if err != nil {
		return err
	}
	// Serialize `QuestProposalBump` param:
	err = encoder.Encode(obj.QuestProposalBump)
	if err != nil {
		return err
	}
	// Serialize `QuestRecorderBump` param:
	err = encoder.Encode(obj.QuestRecorderBump)
	if err != nil {
		return err
	}
	// Serialize `QuestsBump` param:
	err = encoder.Encode(obj.QuestsBump)
	if err != nil {
		return err
	}
	// Serialize `QuestBump` param:
	err = encoder.Encode(obj.QuestBump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *EndQuest) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `QuestProposalIndex`:
	err = decoder.Decode(&obj.QuestProposalIndex)
	if err != nil {
		return err
	}
	// Deserialize `QuestProposalBump`:
	err = decoder.Decode(&obj.QuestProposalBump)
	if err != nil {
		return err
	}
	// Deserialize `QuestRecorderBump`:
	err = decoder.Decode(&obj.QuestRecorderBump)
	if err != nil {
		return err
	}
	// Deserialize `QuestsBump`:
	err = decoder.Decode(&obj.QuestsBump)
	if err != nil {
		return err
	}
	// Deserialize `QuestBump`:
	err = decoder.Decode(&obj.QuestBump)
	if err != nil {
		return err
	}
	return nil
}

// NewEndQuestInstruction declares a new EndQuest instruction with the provided parameters and accounts.
func NewEndQuestInstruction(
	// Parameters:
	questProposalIndex uint64,
	questProposalBump uint8,
	questRecorderBump uint8,
	questsBump uint8,
	questBump uint8,
	// Accounts:
	questRecorder ag_solanago.PublicKey,
	questAcc ag_solanago.PublicKey,
	questProposal ag_solanago.PublicKey,
	quest ag_solanago.PublicKey,
	quests ag_solanago.PublicKey,
	initializer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	slotHashes ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey) *EndQuest {
	return NewEndQuestInstructionBuilder().
		SetQuestProposalIndex(questProposalIndex).
		SetQuestProposalBump(questProposalBump).
		SetQuestRecorderBump(questRecorderBump).
		SetQuestsBump(questsBump).
		SetQuestBump(questBump).
		SetQuestRecorderAccount(questRecorder).
		SetQuestAccAccount(questAcc).
		SetQuestProposalAccount(questProposal).
		SetQuestAccount(quest).
		SetQuestsAccount(quests).
		SetInitializerAccount(initializer).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSlotHashesAccount(slotHashes).
		SetOracleAccount(oracle)
}
