// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EnrollQuestee is the `enrollQuestee` instruction.
type EnrollQuestee struct {

	// [0] = [WRITE, SIGNER] initializer
	//
	// [1] = [WRITE] questee
	//
	// [2] = [] pixelballzMint
	//
	// [3] = [] pixelballzTokenAccount
	//
	// [4] = [] questor
	//
	// [5] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEnrollQuesteeInstructionBuilder creates a new `EnrollQuestee` instruction builder.
func NewEnrollQuesteeInstructionBuilder() *EnrollQuestee {
	nd := &EnrollQuestee{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetInitializerAccount sets the "initializer" account.
func (inst *EnrollQuestee) SetInitializerAccount(initializer ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *EnrollQuestee) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetQuesteeAccount sets the "questee" account.
func (inst *EnrollQuestee) SetQuesteeAccount(questee ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(questee).WRITE()
	return inst
}

// GetQuesteeAccount gets the "questee" account.
func (inst *EnrollQuestee) GetQuesteeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPixelballzMintAccount sets the "pixelballzMint" account.
func (inst *EnrollQuestee) SetPixelballzMintAccount(pixelballzMint ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(pixelballzMint)
	return inst
}

// GetPixelballzMintAccount gets the "pixelballzMint" account.
func (inst *EnrollQuestee) GetPixelballzMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPixelballzTokenAccountAccount sets the "pixelballzTokenAccount" account.
func (inst *EnrollQuestee) SetPixelballzTokenAccountAccount(pixelballzTokenAccount ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(pixelballzTokenAccount)
	return inst
}

// GetPixelballzTokenAccountAccount gets the "pixelballzTokenAccount" account.
func (inst *EnrollQuestee) GetPixelballzTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQuestorAccount sets the "questor" account.
func (inst *EnrollQuestee) SetQuestorAccount(questor ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(questor)
	return inst
}

// GetQuestorAccount gets the "questor" account.
func (inst *EnrollQuestee) GetQuestorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EnrollQuestee) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EnrollQuestee {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EnrollQuestee) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst EnrollQuestee) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EnrollQuestee,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EnrollQuestee) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EnrollQuestee) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Questee is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PixelballzMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.PixelballzTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Questor is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EnrollQuestee) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EnrollQuestee")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    initializer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        questee", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" pixelballzMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("pixelballzToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        questor", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj EnrollQuestee) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EnrollQuestee) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEnrollQuesteeInstruction declares a new EnrollQuestee instruction with the provided parameters and accounts.
func NewEnrollQuesteeInstruction(
	// Accounts:
	initializer ag_solanago.PublicKey,
	questee ag_solanago.PublicKey,
	pixelballzMint ag_solanago.PublicKey,
	pixelballzTokenAccount ag_solanago.PublicKey,
	questor ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EnrollQuestee {
	return NewEnrollQuesteeInstructionBuilder().
		SetInitializerAccount(initializer).
		SetQuesteeAccount(questee).
		SetPixelballzMintAccount(pixelballzMint).
		SetPixelballzTokenAccountAccount(pixelballzTokenAccount).
		SetQuestorAccount(questor).
		SetSystemProgramAccount(systemProgram)
}
