// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RegisterQuestRecorder is the `registerQuestRecorder` instruction.
type RegisterQuestRecorder struct {

	// [0] = [WRITE, SIGNER] initializer
	//
	// [1] = [WRITE] questRecorder
	//
	// [2] = [] quest
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRegisterQuestRecorderInstructionBuilder creates a new `RegisterQuestRecorder` instruction builder.
func NewRegisterQuestRecorderInstructionBuilder() *RegisterQuestRecorder {
	nd := &RegisterQuestRecorder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetInitializerAccount sets the "initializer" account.
func (inst *RegisterQuestRecorder) SetInitializerAccount(initializer ag_solanago.PublicKey) *RegisterQuestRecorder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *RegisterQuestRecorder) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetQuestRecorderAccount sets the "questRecorder" account.
func (inst *RegisterQuestRecorder) SetQuestRecorderAccount(questRecorder ag_solanago.PublicKey) *RegisterQuestRecorder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(questRecorder).WRITE()
	return inst
}

// GetQuestRecorderAccount gets the "questRecorder" account.
func (inst *RegisterQuestRecorder) GetQuestRecorderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetQuestAccount sets the "quest" account.
func (inst *RegisterQuestRecorder) SetQuestAccount(quest ag_solanago.PublicKey) *RegisterQuestRecorder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(quest)
	return inst
}

// GetQuestAccount gets the "quest" account.
func (inst *RegisterQuestRecorder) GetQuestAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RegisterQuestRecorder) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RegisterQuestRecorder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RegisterQuestRecorder) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst RegisterQuestRecorder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RegisterQuestRecorder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RegisterQuestRecorder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RegisterQuestRecorder) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.QuestRecorder is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Quest is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RegisterQuestRecorder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RegisterQuestRecorder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  initializer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("questRecorder", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        quest", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj RegisterQuestRecorder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RegisterQuestRecorder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRegisterQuestRecorderInstruction declares a new RegisterQuestRecorder instruction with the provided parameters and accounts.
func NewRegisterQuestRecorderInstruction(
	// Accounts:
	initializer ag_solanago.PublicKey,
	questRecorder ag_solanago.PublicKey,
	quest ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RegisterQuestRecorder {
	return NewRegisterQuestRecorderInstructionBuilder().
		SetInitializerAccount(initializer).
		SetQuestRecorderAccount(questRecorder).
		SetQuestAccount(quest).
		SetSystemProgramAccount(systemProgram)
}
