// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RegisterQuestsStakingReward is the `registerQuestsStakingReward` instruction.
type RegisterQuestsStakingReward struct {
	QuestsBump *uint8
	Name       *string
	Symbol     *string
	Uri        *string

	// [0] = [WRITE, SIGNER] oracle
	//
	// [1] = [] quests
	//
	// [2] = [WRITE, SIGNER] rewardMint
	//
	// [3] = [] systemProgram
	//
	// [4] = [] tokenProgram
	//
	// [5] = [] mplMetadataProgram
	//
	// [6] = [WRITE] metadataAccount
	//
	// [7] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRegisterQuestsStakingRewardInstructionBuilder creates a new `RegisterQuestsStakingReward` instruction builder.
func NewRegisterQuestsStakingRewardInstructionBuilder() *RegisterQuestsStakingReward {
	nd := &RegisterQuestsStakingReward{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetQuestsBump sets the "questsBump" parameter.
func (inst *RegisterQuestsStakingReward) SetQuestsBump(questsBump uint8) *RegisterQuestsStakingReward {
	inst.QuestsBump = &questsBump
	return inst
}

// SetName sets the "name" parameter.
func (inst *RegisterQuestsStakingReward) SetName(name string) *RegisterQuestsStakingReward {
	inst.Name = &name
	return inst
}

// SetSymbol sets the "symbol" parameter.
func (inst *RegisterQuestsStakingReward) SetSymbol(symbol string) *RegisterQuestsStakingReward {
	inst.Symbol = &symbol
	return inst
}

// SetUri sets the "uri" parameter.
func (inst *RegisterQuestsStakingReward) SetUri(uri string) *RegisterQuestsStakingReward {
	inst.Uri = &uri
	return inst
}

// SetOracleAccount sets the "oracle" account.
func (inst *RegisterQuestsStakingReward) SetOracleAccount(oracle ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(oracle).WRITE().SIGNER()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *RegisterQuestsStakingReward) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetQuestsAccount sets the "quests" account.
func (inst *RegisterQuestsStakingReward) SetQuestsAccount(quests ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(quests)
	return inst
}

// GetQuestsAccount gets the "quests" account.
func (inst *RegisterQuestsStakingReward) GetQuestsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRewardMintAccount sets the "rewardMint" account.
func (inst *RegisterQuestsStakingReward) SetRewardMintAccount(rewardMint ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rewardMint).WRITE().SIGNER()
	return inst
}

// GetRewardMintAccount gets the "rewardMint" account.
func (inst *RegisterQuestsStakingReward) GetRewardMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RegisterQuestsStakingReward) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RegisterQuestsStakingReward) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *RegisterQuestsStakingReward) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *RegisterQuestsStakingReward) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMplMetadataProgramAccount sets the "mplMetadataProgram" account.
func (inst *RegisterQuestsStakingReward) SetMplMetadataProgramAccount(mplMetadataProgram ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mplMetadataProgram)
	return inst
}

// GetMplMetadataProgramAccount gets the "mplMetadataProgram" account.
func (inst *RegisterQuestsStakingReward) GetMplMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMetadataAccountAccount sets the "metadataAccount" account.
func (inst *RegisterQuestsStakingReward) SetMetadataAccountAccount(metadataAccount ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(metadataAccount).WRITE()
	return inst
}

// GetMetadataAccountAccount gets the "metadataAccount" account.
func (inst *RegisterQuestsStakingReward) GetMetadataAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentAccount sets the "rent" account.
func (inst *RegisterQuestsStakingReward) SetRentAccount(rent ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *RegisterQuestsStakingReward) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst RegisterQuestsStakingReward) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RegisterQuestsStakingReward,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RegisterQuestsStakingReward) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RegisterQuestsStakingReward) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.QuestsBump == nil {
			return errors.New("QuestsBump parameter is not set")
		}
		if inst.Name == nil {
			return errors.New("Name parameter is not set")
		}
		if inst.Symbol == nil {
			return errors.New("Symbol parameter is not set")
		}
		if inst.Uri == nil {
			return errors.New("Uri parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Quests is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.RewardMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.MplMetadataProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.MetadataAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *RegisterQuestsStakingReward) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RegisterQuestsStakingReward")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("QuestsBump", *inst.QuestsBump))
						paramsBranch.Child(ag_format.Param("      Name", *inst.Name))
						paramsBranch.Child(ag_format.Param("    Symbol", *inst.Symbol))
						paramsBranch.Child(ag_format.Param("       Uri", *inst.Uri))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("            oracle", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            quests", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        rewardMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("     systemProgram", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("      tokenProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("mplMetadataProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("          metadata", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("              rent", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj RegisterQuestsStakingReward) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `QuestsBump` param:
	err = encoder.Encode(obj.QuestsBump)
	if err != nil {
		return err
	}
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Symbol` param:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return err
	}
	// Serialize `Uri` param:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RegisterQuestsStakingReward) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `QuestsBump`:
	err = decoder.Decode(&obj.QuestsBump)
	if err != nil {
		return err
	}
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return err
	}
	// Deserialize `Uri`:
	err = decoder.Decode(&obj.Uri)
	if err != nil {
		return err
	}
	return nil
}

// NewRegisterQuestsStakingRewardInstruction declares a new RegisterQuestsStakingReward instruction with the provided parameters and accounts.
func NewRegisterQuestsStakingRewardInstruction(
	// Parameters:
	questsBump uint8,
	name string,
	symbol string,
	uri string,
	// Accounts:
	oracle ag_solanago.PublicKey,
	quests ag_solanago.PublicKey,
	rewardMint ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	mplMetadataProgram ag_solanago.PublicKey,
	metadataAccount ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *RegisterQuestsStakingReward {
	return NewRegisterQuestsStakingRewardInstructionBuilder().
		SetQuestsBump(questsBump).
		SetName(name).
		SetSymbol(symbol).
		SetUri(uri).
		SetOracleAccount(oracle).
		SetQuestsAccount(quests).
		SetRewardMintAccount(rewardMint).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetMplMetadataProgramAccount(mplMetadataProgram).
		SetMetadataAccountAccount(metadataAccount).
		SetRentAccount(rent)
}
