// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package flipper

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// NewFlip is the `newFlip` instruction.
type NewFlip struct {
	HouseBump  *uint8
	FlipBump   *uint8
	EscrowBump *uint8
	DailyEpoch *uint64
	Operator   *string
	Amount     *uint64
	Selection  *uint8

	// [0] = [WRITE, SIGNER] initializer
	//
	// [1] = [WRITE] fees
	//
	// [2] = [WRITE] escrow
	//
	// [3] = [] escrowProgram
	//
	// [4] = [WRITE] oracle
	//
	// [5] = [WRITE] house
	//
	// [6] = [WRITE] flip
	//
	// [7] = [] systemProgram
	//
	// [8] = [] flipperProgram
	//
	// [9] = [] slotHashes
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewNewFlipInstructionBuilder creates a new `NewFlip` instruction builder.
func NewNewFlipInstructionBuilder() *NewFlip {
	nd := &NewFlip{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetHouseBump sets the "houseBump" parameter.
func (inst *NewFlip) SetHouseBump(houseBump uint8) *NewFlip {
	inst.HouseBump = &houseBump
	return inst
}

// SetFlipBump sets the "flipBump" parameter.
func (inst *NewFlip) SetFlipBump(flipBump uint8) *NewFlip {
	inst.FlipBump = &flipBump
	return inst
}

// SetEscrowBump sets the "escrowBump" parameter.
func (inst *NewFlip) SetEscrowBump(escrowBump uint8) *NewFlip {
	inst.EscrowBump = &escrowBump
	return inst
}

// SetDailyEpoch sets the "dailyEpoch" parameter.
func (inst *NewFlip) SetDailyEpoch(dailyEpoch uint64) *NewFlip {
	inst.DailyEpoch = &dailyEpoch
	return inst
}

// SetOperator sets the "operator" parameter.
func (inst *NewFlip) SetOperator(operator string) *NewFlip {
	inst.Operator = &operator
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *NewFlip) SetAmount(amount uint64) *NewFlip {
	inst.Amount = &amount
	return inst
}

// SetSelection sets the "selection" parameter.
func (inst *NewFlip) SetSelection(selection uint8) *NewFlip {
	inst.Selection = &selection
	return inst
}

// SetInitializerAccount sets the "initializer" account.
func (inst *NewFlip) SetInitializerAccount(initializer ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *NewFlip) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFeesAccount sets the "fees" account.
func (inst *NewFlip) SetFeesAccount(fees ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(fees).WRITE()
	return inst
}

// GetFeesAccount gets the "fees" account.
func (inst *NewFlip) GetFeesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *NewFlip) SetEscrowAccount(escrow ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *NewFlip) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetEscrowProgramAccount sets the "escrowProgram" account.
func (inst *NewFlip) SetEscrowProgramAccount(escrowProgram ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(escrowProgram)
	return inst
}

// GetEscrowProgramAccount gets the "escrowProgram" account.
func (inst *NewFlip) GetEscrowProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOracleAccount sets the "oracle" account.
func (inst *NewFlip) SetOracleAccount(oracle ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(oracle).WRITE()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *NewFlip) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetHouseAccount sets the "house" account.
func (inst *NewFlip) SetHouseAccount(house ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(house).WRITE()
	return inst
}

// GetHouseAccount gets the "house" account.
func (inst *NewFlip) GetHouseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetFlipAccount sets the "flip" account.
func (inst *NewFlip) SetFlipAccount(flip ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(flip).WRITE()
	return inst
}

// GetFlipAccount gets the "flip" account.
func (inst *NewFlip) GetFlipAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *NewFlip) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *NewFlip) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetFlipperProgramAccount sets the "flipperProgram" account.
func (inst *NewFlip) SetFlipperProgramAccount(flipperProgram ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(flipperProgram)
	return inst
}

// GetFlipperProgramAccount gets the "flipperProgram" account.
func (inst *NewFlip) GetFlipperProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSlotHashesAccount sets the "slotHashes" account.
func (inst *NewFlip) SetSlotHashesAccount(slotHashes ag_solanago.PublicKey) *NewFlip {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(slotHashes)
	return inst
}

// GetSlotHashesAccount gets the "slotHashes" account.
func (inst *NewFlip) GetSlotHashesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst NewFlip) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_NewFlip,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst NewFlip) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *NewFlip) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.HouseBump == nil {
			return errors.New("HouseBump parameter is not set")
		}
		if inst.FlipBump == nil {
			return errors.New("FlipBump parameter is not set")
		}
		if inst.EscrowBump == nil {
			return errors.New("EscrowBump parameter is not set")
		}
		if inst.DailyEpoch == nil {
			return errors.New("DailyEpoch parameter is not set")
		}
		if inst.Operator == nil {
			return errors.New("Operator parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.Selection == nil {
			return errors.New("Selection parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Fees is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.EscrowProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.House is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Flip is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.FlipperProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SlotHashes is not set")
		}
	}
	return nil
}

func (inst *NewFlip) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("NewFlip")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=7]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" HouseBump", *inst.HouseBump))
						paramsBranch.Child(ag_format.Param("  FlipBump", *inst.FlipBump))
						paramsBranch.Child(ag_format.Param("EscrowBump", *inst.EscrowBump))
						paramsBranch.Child(ag_format.Param("DailyEpoch", *inst.DailyEpoch))
						paramsBranch.Child(ag_format.Param("  Operator", *inst.Operator))
						paramsBranch.Child(ag_format.Param("    Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param(" Selection", *inst.Selection))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   initializer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          fees", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        escrow", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" escrowProgram", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        oracle", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         house", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("          flip", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta(" systemProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("flipperProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("    slotHashes", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj NewFlip) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `HouseBump` param:
	err = encoder.Encode(obj.HouseBump)
	if err != nil {
		return err
	}
	// Serialize `FlipBump` param:
	err = encoder.Encode(obj.FlipBump)
	if err != nil {
		return err
	}
	// Serialize `EscrowBump` param:
	err = encoder.Encode(obj.EscrowBump)
	if err != nil {
		return err
	}
	// Serialize `DailyEpoch` param:
	err = encoder.Encode(obj.DailyEpoch)
	if err != nil {
		return err
	}
	// Serialize `Operator` param:
	err = encoder.Encode(obj.Operator)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `Selection` param:
	err = encoder.Encode(obj.Selection)
	if err != nil {
		return err
	}
	return nil
}
func (obj *NewFlip) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `HouseBump`:
	err = decoder.Decode(&obj.HouseBump)
	if err != nil {
		return err
	}
	// Deserialize `FlipBump`:
	err = decoder.Decode(&obj.FlipBump)
	if err != nil {
		return err
	}
	// Deserialize `EscrowBump`:
	err = decoder.Decode(&obj.EscrowBump)
	if err != nil {
		return err
	}
	// Deserialize `DailyEpoch`:
	err = decoder.Decode(&obj.DailyEpoch)
	if err != nil {
		return err
	}
	// Deserialize `Operator`:
	err = decoder.Decode(&obj.Operator)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `Selection`:
	err = decoder.Decode(&obj.Selection)
	if err != nil {
		return err
	}
	return nil
}

// NewNewFlipInstruction declares a new NewFlip instruction with the provided parameters and accounts.
func NewNewFlipInstruction(
	// Parameters:
	houseBump uint8,
	flipBump uint8,
	escrowBump uint8,
	dailyEpoch uint64,
	operator string,
	amount uint64,
	selection uint8,
	// Accounts:
	initializer ag_solanago.PublicKey,
	fees ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	escrowProgram ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	house ag_solanago.PublicKey,
	flip ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	flipperProgram ag_solanago.PublicKey,
	slotHashes ag_solanago.PublicKey) *NewFlip {
	return NewNewFlipInstructionBuilder().
		SetHouseBump(houseBump).
		SetFlipBump(flipBump).
		SetEscrowBump(escrowBump).
		SetDailyEpoch(dailyEpoch).
		SetOperator(operator).
		SetAmount(amount).
		SetSelection(selection).
		SetInitializerAccount(initializer).
		SetFeesAccount(fees).
		SetEscrowAccount(escrow).
		SetEscrowProgramAccount(escrowProgram).
		SetOracleAccount(oracle).
		SetHouseAccount(house).
		SetFlipAccount(flip).
		SetSystemProgramAccount(systemProgram).
		SetFlipperProgramAccount(flipperProgram).
		SetSlotHashesAccount(slotHashes)
}
