// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package blackjack

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// PlayerTurn is the `playerTurn` instruction.
type PlayerTurn struct {
	HouseBump  *uint8
	StatsBump  *uint8
	EscrowBump *uint8
	DailyEpoch *uint64
	GameBump   *uint8
	GameIndex  *uint64
	Operator   *string

	// [0] = [WRITE] game
	//
	// [1] = [WRITE, SIGNER] initializer
	//
	// [2] = [WRITE] escrow
	//
	// [3] = [] escrowProgram
	//
	// [4] = [WRITE] oracle
	//
	// [5] = [WRITE] house
	//
	// [6] = [WRITE] stats
	//
	// [7] = [] systemProgram
	//
	// [8] = [] blackjackProgram
	//
	// [9] = [] slotHashes
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewPlayerTurnInstructionBuilder creates a new `PlayerTurn` instruction builder.
func NewPlayerTurnInstructionBuilder() *PlayerTurn {
	nd := &PlayerTurn{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetHouseBump sets the "houseBump" parameter.
func (inst *PlayerTurn) SetHouseBump(houseBump uint8) *PlayerTurn {
	inst.HouseBump = &houseBump
	return inst
}

// SetStatsBump sets the "statsBump" parameter.
func (inst *PlayerTurn) SetStatsBump(statsBump uint8) *PlayerTurn {
	inst.StatsBump = &statsBump
	return inst
}

// SetEscrowBump sets the "escrowBump" parameter.
func (inst *PlayerTurn) SetEscrowBump(escrowBump uint8) *PlayerTurn {
	inst.EscrowBump = &escrowBump
	return inst
}

// SetDailyEpoch sets the "dailyEpoch" parameter.
func (inst *PlayerTurn) SetDailyEpoch(dailyEpoch uint64) *PlayerTurn {
	inst.DailyEpoch = &dailyEpoch
	return inst
}

// SetGameBump sets the "gameBump" parameter.
func (inst *PlayerTurn) SetGameBump(gameBump uint8) *PlayerTurn {
	inst.GameBump = &gameBump
	return inst
}

// SetGameIndex sets the "gameIndex" parameter.
func (inst *PlayerTurn) SetGameIndex(gameIndex uint64) *PlayerTurn {
	inst.GameIndex = &gameIndex
	return inst
}

// SetOperator sets the "operator" parameter.
func (inst *PlayerTurn) SetOperator(operator string) *PlayerTurn {
	inst.Operator = &operator
	return inst
}

// SetGameAccount sets the "game" account.
func (inst *PlayerTurn) SetGameAccount(game ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(game).WRITE()
	return inst
}

// GetGameAccount gets the "game" account.
func (inst *PlayerTurn) GetGameAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetInitializerAccount sets the "initializer" account.
func (inst *PlayerTurn) SetInitializerAccount(initializer ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *PlayerTurn) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *PlayerTurn) SetEscrowAccount(escrow ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *PlayerTurn) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetEscrowProgramAccount sets the "escrowProgram" account.
func (inst *PlayerTurn) SetEscrowProgramAccount(escrowProgram ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(escrowProgram)
	return inst
}

// GetEscrowProgramAccount gets the "escrowProgram" account.
func (inst *PlayerTurn) GetEscrowProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOracleAccount sets the "oracle" account.
func (inst *PlayerTurn) SetOracleAccount(oracle ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(oracle).WRITE()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *PlayerTurn) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetHouseAccount sets the "house" account.
func (inst *PlayerTurn) SetHouseAccount(house ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(house).WRITE()
	return inst
}

// GetHouseAccount gets the "house" account.
func (inst *PlayerTurn) GetHouseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStatsAccount sets the "stats" account.
func (inst *PlayerTurn) SetStatsAccount(stats ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stats).WRITE()
	return inst
}

// GetStatsAccount gets the "stats" account.
func (inst *PlayerTurn) GetStatsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *PlayerTurn) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *PlayerTurn) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetBlackjackProgramAccount sets the "blackjackProgram" account.
func (inst *PlayerTurn) SetBlackjackProgramAccount(blackjackProgram ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(blackjackProgram)
	return inst
}

// GetBlackjackProgramAccount gets the "blackjackProgram" account.
func (inst *PlayerTurn) GetBlackjackProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSlotHashesAccount sets the "slotHashes" account.
func (inst *PlayerTurn) SetSlotHashesAccount(slotHashes ag_solanago.PublicKey) *PlayerTurn {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(slotHashes)
	return inst
}

// GetSlotHashesAccount gets the "slotHashes" account.
func (inst *PlayerTurn) GetSlotHashesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst PlayerTurn) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_PlayerTurn,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst PlayerTurn) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *PlayerTurn) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.HouseBump == nil {
			return errors.New("HouseBump parameter is not set")
		}
		if inst.StatsBump == nil {
			return errors.New("StatsBump parameter is not set")
		}
		if inst.EscrowBump == nil {
			return errors.New("EscrowBump parameter is not set")
		}
		if inst.DailyEpoch == nil {
			return errors.New("DailyEpoch parameter is not set")
		}
		if inst.GameBump == nil {
			return errors.New("GameBump parameter is not set")
		}
		if inst.GameIndex == nil {
			return errors.New("GameIndex parameter is not set")
		}
		if inst.Operator == nil {
			return errors.New("Operator parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Game is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.EscrowProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.House is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Stats is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.BlackjackProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SlotHashes is not set")
		}
	}
	return nil
}

func (inst *PlayerTurn) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("PlayerTurn")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=7]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" HouseBump", *inst.HouseBump))
						paramsBranch.Child(ag_format.Param(" StatsBump", *inst.StatsBump))
						paramsBranch.Child(ag_format.Param("EscrowBump", *inst.EscrowBump))
						paramsBranch.Child(ag_format.Param("DailyEpoch", *inst.DailyEpoch))
						paramsBranch.Child(ag_format.Param("  GameBump", *inst.GameBump))
						paramsBranch.Child(ag_format.Param(" GameIndex", *inst.GameIndex))
						paramsBranch.Child(ag_format.Param("  Operator", *inst.Operator))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("            game", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     initializer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          escrow", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   escrowProgram", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          oracle", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("           house", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           stats", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("   systemProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("blackjackProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("      slotHashes", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj PlayerTurn) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `HouseBump` param:
	err = encoder.Encode(obj.HouseBump)
	if err != nil {
		return err
	}
	// Serialize `StatsBump` param:
	err = encoder.Encode(obj.StatsBump)
	if err != nil {
		return err
	}
	// Serialize `EscrowBump` param:
	err = encoder.Encode(obj.EscrowBump)
	if err != nil {
		return err
	}
	// Serialize `DailyEpoch` param:
	err = encoder.Encode(obj.DailyEpoch)
	if err != nil {
		return err
	}
	// Serialize `GameBump` param:
	err = encoder.Encode(obj.GameBump)
	if err != nil {
		return err
	}
	// Serialize `GameIndex` param:
	err = encoder.Encode(obj.GameIndex)
	if err != nil {
		return err
	}
	// Serialize `Operator` param:
	err = encoder.Encode(obj.Operator)
	if err != nil {
		return err
	}
	return nil
}
func (obj *PlayerTurn) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `HouseBump`:
	err = decoder.Decode(&obj.HouseBump)
	if err != nil {
		return err
	}
	// Deserialize `StatsBump`:
	err = decoder.Decode(&obj.StatsBump)
	if err != nil {
		return err
	}
	// Deserialize `EscrowBump`:
	err = decoder.Decode(&obj.EscrowBump)
	if err != nil {
		return err
	}
	// Deserialize `DailyEpoch`:
	err = decoder.Decode(&obj.DailyEpoch)
	if err != nil {
		return err
	}
	// Deserialize `GameBump`:
	err = decoder.Decode(&obj.GameBump)
	if err != nil {
		return err
	}
	// Deserialize `GameIndex`:
	err = decoder.Decode(&obj.GameIndex)
	if err != nil {
		return err
	}
	// Deserialize `Operator`:
	err = decoder.Decode(&obj.Operator)
	if err != nil {
		return err
	}
	return nil
}

// NewPlayerTurnInstruction declares a new PlayerTurn instruction with the provided parameters and accounts.
func NewPlayerTurnInstruction(
	// Parameters:
	houseBump uint8,
	statsBump uint8,
	escrowBump uint8,
	dailyEpoch uint64,
	gameBump uint8,
	gameIndex uint64,
	operator string,
	// Accounts:
	game ag_solanago.PublicKey,
	initializer ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	escrowProgram ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	house ag_solanago.PublicKey,
	stats ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	blackjackProgram ag_solanago.PublicKey,
	slotHashes ag_solanago.PublicKey) *PlayerTurn {
	return NewPlayerTurnInstructionBuilder().
		SetHouseBump(houseBump).
		SetStatsBump(statsBump).
		SetEscrowBump(escrowBump).
		SetDailyEpoch(dailyEpoch).
		SetGameBump(gameBump).
		SetGameIndex(gameIndex).
		SetOperator(operator).
		SetGameAccount(game).
		SetInitializerAccount(initializer).
		SetEscrowAccount(escrow).
		SetEscrowProgramAccount(escrowProgram).
		SetOracleAccount(oracle).
		SetHouseAccount(house).
		SetStatsAccount(stats).
		SetSystemProgramAccount(systemProgram).
		SetBlackjackProgramAccount(blackjackProgram).
		SetSlotHashesAccount(slotHashes)
}
