// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package draffle

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ClaimPrize is the `claimPrize` instruction.
type ClaimPrize struct {
	PrizeIndex  *uint32
	TicketIndex *uint32

	// [0] = [WRITE] raffle
	//
	// [1] = [] entrants
	//
	// [2] = [WRITE] prize
	//
	// [3] = [WRITE] winnerTokenAccount
	//
	// [4] = [WRITE, SIGNER] payer
	//
	// [5] = [WRITE] feeAcc
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewClaimPrizeInstructionBuilder creates a new `ClaimPrize` instruction builder.
func NewClaimPrizeInstructionBuilder() *ClaimPrize {
	nd := &ClaimPrize{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetPrizeIndex sets the "prizeIndex" parameter.
func (inst *ClaimPrize) SetPrizeIndex(prizeIndex uint32) *ClaimPrize {
	inst.PrizeIndex = &prizeIndex
	return inst
}

// SetTicketIndex sets the "ticketIndex" parameter.
func (inst *ClaimPrize) SetTicketIndex(ticketIndex uint32) *ClaimPrize {
	inst.TicketIndex = &ticketIndex
	return inst
}

// SetRaffleAccount sets the "raffle" account.
func (inst *ClaimPrize) SetRaffleAccount(raffle ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(raffle).WRITE()
	return inst
}

// GetRaffleAccount gets the "raffle" account.
func (inst *ClaimPrize) GetRaffleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetEntrantsAccount sets the "entrants" account.
func (inst *ClaimPrize) SetEntrantsAccount(entrants ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(entrants)
	return inst
}

// GetEntrantsAccount gets the "entrants" account.
func (inst *ClaimPrize) GetEntrantsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPrizeAccount sets the "prize" account.
func (inst *ClaimPrize) SetPrizeAccount(prize ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(prize).WRITE()
	return inst
}

// GetPrizeAccount gets the "prize" account.
func (inst *ClaimPrize) GetPrizeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetWinnerTokenAccountAccount sets the "winnerTokenAccount" account.
func (inst *ClaimPrize) SetWinnerTokenAccountAccount(winnerTokenAccount ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(winnerTokenAccount).WRITE()
	return inst
}

// GetWinnerTokenAccountAccount gets the "winnerTokenAccount" account.
func (inst *ClaimPrize) GetWinnerTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPayerAccount sets the "payer" account.
func (inst *ClaimPrize) SetPayerAccount(payer ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *ClaimPrize) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetFeeAccAccount sets the "feeAcc" account.
func (inst *ClaimPrize) SetFeeAccAccount(feeAcc ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(feeAcc).WRITE()
	return inst
}

// GetFeeAccAccount gets the "feeAcc" account.
func (inst *ClaimPrize) GetFeeAccAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *ClaimPrize) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *ClaimPrize) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *ClaimPrize) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *ClaimPrize {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *ClaimPrize) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst ClaimPrize) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ClaimPrize,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ClaimPrize) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ClaimPrize) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.PrizeIndex == nil {
			return errors.New("PrizeIndex parameter is not set")
		}
		if inst.TicketIndex == nil {
			return errors.New("TicketIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Raffle is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Entrants is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Prize is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.WinnerTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.FeeAcc is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *ClaimPrize) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ClaimPrize")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" PrizeIndex", *inst.PrizeIndex))
						paramsBranch.Child(ag_format.Param("TicketIndex", *inst.TicketIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       raffle", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     entrants", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        prize", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("  winnerToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       feeAcc", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj ClaimPrize) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `PrizeIndex` param:
	err = encoder.Encode(obj.PrizeIndex)
	if err != nil {
		return err
	}
	// Serialize `TicketIndex` param:
	err = encoder.Encode(obj.TicketIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ClaimPrize) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `PrizeIndex`:
	err = decoder.Decode(&obj.PrizeIndex)
	if err != nil {
		return err
	}
	// Deserialize `TicketIndex`:
	err = decoder.Decode(&obj.TicketIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewClaimPrizeInstruction declares a new ClaimPrize instruction with the provided parameters and accounts.
func NewClaimPrizeInstruction(
	// Parameters:
	prizeIndex uint32,
	ticketIndex uint32,
	// Accounts:
	raffle ag_solanago.PublicKey,
	entrants ag_solanago.PublicKey,
	prize ag_solanago.PublicKey,
	winnerTokenAccount ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	feeAcc ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *ClaimPrize {
	return NewClaimPrizeInstructionBuilder().
		SetPrizeIndex(prizeIndex).
		SetTicketIndex(ticketIndex).
		SetRaffleAccount(raffle).
		SetEntrantsAccount(entrants).
		SetPrizeAccount(prize).
		SetWinnerTokenAccountAccount(winnerTokenAccount).
		SetPayerAccount(payer).
		SetFeeAccAccount(feeAcc).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
