// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package draffle

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CloseEntrants is the `closeEntrants` instruction.
type CloseEntrants struct {

	// [0] = [] raffle
	//
	// [1] = [WRITE] entrants
	//
	// [2] = [SIGNER] creator
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCloseEntrantsInstructionBuilder creates a new `CloseEntrants` instruction builder.
func NewCloseEntrantsInstructionBuilder() *CloseEntrants {
	nd := &CloseEntrants{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetRaffleAccount sets the "raffle" account.
func (inst *CloseEntrants) SetRaffleAccount(raffle ag_solanago.PublicKey) *CloseEntrants {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(raffle)
	return inst
}

// GetRaffleAccount gets the "raffle" account.
func (inst *CloseEntrants) GetRaffleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetEntrantsAccount sets the "entrants" account.
func (inst *CloseEntrants) SetEntrantsAccount(entrants ag_solanago.PublicKey) *CloseEntrants {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(entrants).WRITE()
	return inst
}

// GetEntrantsAccount gets the "entrants" account.
func (inst *CloseEntrants) GetEntrantsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCreatorAccount sets the "creator" account.
func (inst *CloseEntrants) SetCreatorAccount(creator ag_solanago.PublicKey) *CloseEntrants {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(creator).SIGNER()
	return inst
}

// GetCreatorAccount gets the "creator" account.
func (inst *CloseEntrants) GetCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst CloseEntrants) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CloseEntrants,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CloseEntrants) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CloseEntrants) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Raffle is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Entrants is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Creator is not set")
		}
	}
	return nil
}

func (inst *CloseEntrants) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CloseEntrants")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  raffle", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("entrants", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" creator", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj CloseEntrants) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CloseEntrants) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCloseEntrantsInstruction declares a new CloseEntrants instruction with the provided parameters and accounts.
func NewCloseEntrantsInstruction(
	// Accounts:
	raffle ag_solanago.PublicKey,
	entrants ag_solanago.PublicKey,
	creator ag_solanago.PublicKey) *CloseEntrants {
	return NewCloseEntrantsInstructionBuilder().
		SetRaffleAccount(raffle).
		SetEntrantsAccount(entrants).
		SetCreatorAccount(creator)
}
