// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package draffle

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "Draffle"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	Instruction_CreateRaffle = ag_binary.TypeID([8]byte{226, 206, 159, 34, 213, 207, 98, 126})

	Instruction_AddPrize = ag_binary.TypeID([8]byte{72, 182, 203, 140, 3, 163, 192, 98})

	Instruction_ReclaimPrize = ag_binary.TypeID([8]byte{74, 240, 215, 247, 126, 227, 246, 135})

	Instruction_BuyTickets = ag_binary.TypeID([8]byte{48, 16, 122, 137, 24, 214, 198, 58})

	Instruction_RevealWinners = ag_binary.TypeID([8]byte{24, 167, 123, 197, 91, 200, 146, 3})

	Instruction_ClaimPrize = ag_binary.TypeID([8]byte{157, 233, 139, 121, 246, 62, 234, 235})

	Instruction_CollectProceeds = ag_binary.TypeID([8]byte{244, 144, 47, 7, 238, 154, 18, 160})

	Instruction_CloseEntrants = ag_binary.TypeID([8]byte{241, 25, 87, 232, 155, 81, 232, 179})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_CreateRaffle:
		return "CreateRaffle"
	case Instruction_AddPrize:
		return "AddPrize"
	case Instruction_ReclaimPrize:
		return "ReclaimPrize"
	case Instruction_BuyTickets:
		return "BuyTickets"
	case Instruction_RevealWinners:
		return "RevealWinners"
	case Instruction_ClaimPrize:
		return "ClaimPrize"
	case Instruction_CollectProceeds:
		return "CollectProceeds"
	case Instruction_CloseEntrants:
		return "CloseEntrants"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"create_raffle", (*CreateRaffle)(nil),
		},
		{
			"add_prize", (*AddPrize)(nil),
		},
		{
			"reclaim_prize", (*ReclaimPrize)(nil),
		},
		{
			"buy_tickets", (*BuyTickets)(nil),
		},
		{
			"reveal_winners", (*RevealWinners)(nil),
		},
		{
			"claim_prize", (*ClaimPrize)(nil),
		},
		{
			"collect_proceeds", (*CollectProceeds)(nil),
		},
		{
			"close_entrants", (*CloseEntrants)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
