// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package draffle

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RevealWinners is the `revealWinners` instruction.
type RevealWinners struct {

	// [0] = [WRITE] raffle
	//
	// [1] = [] recentBlockhashes
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRevealWinnersInstructionBuilder creates a new `RevealWinners` instruction builder.
func NewRevealWinnersInstructionBuilder() *RevealWinners {
	nd := &RevealWinners{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetRaffleAccount sets the "raffle" account.
func (inst *RevealWinners) SetRaffleAccount(raffle ag_solanago.PublicKey) *RevealWinners {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(raffle).WRITE()
	return inst
}

// GetRaffleAccount gets the "raffle" account.
func (inst *RevealWinners) GetRaffleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRecentBlockhashesAccount sets the "recentBlockhashes" account.
func (inst *RevealWinners) SetRecentBlockhashesAccount(recentBlockhashes ag_solanago.PublicKey) *RevealWinners {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(recentBlockhashes)
	return inst
}

// GetRecentBlockhashesAccount gets the "recentBlockhashes" account.
func (inst *RevealWinners) GetRecentBlockhashesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst RevealWinners) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RevealWinners,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RevealWinners) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RevealWinners) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Raffle is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RecentBlockhashes is not set")
		}
	}
	return nil
}

func (inst *RevealWinners) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RevealWinners")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("           raffle", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("recentBlockhashes", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj RevealWinners) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RevealWinners) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRevealWinnersInstruction declares a new RevealWinners instruction with the provided parameters and accounts.
func NewRevealWinnersInstruction(
	// Accounts:
	raffle ag_solanago.PublicKey,
	recentBlockhashes ag_solanago.PublicKey) *RevealWinners {
	return NewRevealWinnersInstructionBuilder().
		SetRaffleAccount(raffle).
		SetRecentBlockhashesAccount(recentBlockhashes)
}
